language: node_js
node_js:
- '11'
addons:
  chrome: stable
before_script:
- npm run lint
- cp test/index.all.html test/index.html
# `cp` because of https://github.com/Polymer/tools/issues/416#issue-327241592
- cp wct.conf.local.json wct.conf.json
- polymer test
script:
- cp test/index.high-priority.html test/index.html
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    cp wct.conf.sauce-chrome.json wct.conf.json;
    polymer test || travis_terminate 1;

    cp wct.conf.sauce-firefox.json wct.conf.json;
    polymer test || travis_terminate 1;

    cp wct.conf.sauce-others.json wct.conf.json;
    polymer test || travis_terminate 1;
  fi'
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - OWNER_NAME=Brightspace
  - REPO_NAME=d2l-my-courses-ui
  # SAUCE_USERNAME
  - secure: UniblxNZpjPqb43+ogtl9htJf4M/ityvtdii+d6x3+cKG5gCBzUPASorYnT3RuM/KGp2leeA2a+i9gThEZMZZEr9xy98gazOp9dUM5NR79MCgDKfUTpxD7r/scLKd4kV7wTqtzHWVembQwoVkR9DVu38Fevy6EbsWhAmfKoG2axL8/45vs7llyw+LhI4U9ew4nN9VmWpsdxlvUGtxCummLk0e1rN32nYmiejcoGY4Y/IBIZBK62E2DPZLT3bxbrP3fIHogn7eiOt/1knt89POU9wuOuIpe+vLs57UEKxzZi5SaJqaoAekuvWc5MP2iayJHeRCTkoZXSZ8NYfDavns3GGIYU5MjhVVTwOTVmOkg2c5ai8tSfkAdP5oS7EyHEsqAdOWkuxf8LQYR+dlVmIg604ZoxyPmu6cFQmpUHF0+GwDAKfoKsXlupiRydkipFrCwE8prVQEfL3qiBPVyVfugLZwHQbewMPLJaSqpTzmu2WEnloS933AOruH2GPj664VrCih9HPUd795eitE8jyqNGl9t69cKRLCLUcawaXH5eJYP9W6E6ZdQxGvnycba1KJpLgbtkHNfUhrkbhBh62sUqGEh1ylEsMlAf7cZUenrk2ViSxQm4+swDgfmWPQh2u743DmIcOiIeIbiPOyj/ZU5+ZFR763PQ71/zIr78WQys=
  # SAUCE_ACCESS_KEY
  - secure: OONg1ddGCjI+rx4oFrUKBy9pbkPYAU2xS3pm52SfMzW1MWK04grN6u96DXK/uScx+8dfEZltSBIIMTaJuu/OAOo7rd2fFlgSm10FFHIsc4cGTumqeZpFPzDdB0GMcHiERSjZ6BVQpUfHprdkbpWi178G5EPGrXjXJ1tRP+7p70pvk8SBrxm5nq6J2wMs45zW9hKMYUZVmBF/wfddK6PS+xy6eDwraBxku4pEcsm8Lbl/lhkj+B2aLEFXKTCpXEFD5sPLqQVRoPP7Y9Zrl1sUShOMOlVbIuMfoQDgfKWR5HPwYjKg3lSZP2TSj6eJyZtfAgiR9xHoZxABEMQw/Q17FMAYTpf9zc71TehlH7vCxqfYzTt8t+ZnSwwJTH/s9b4aKUSsCc6e7kkBHzvpkKZHfhyPeMfG0nCWn9JvJfNekhkCVrLK0+p18z+hyTiJ1TdWXc/Uvi6gPYhvfwYcnsFoiE9HcADhlt2VWOilADWG0kLWsh8R+D8txzOfKtorYGFzHS0IXR8F1IXlV8P3fQ1HVWrN2VYfxRNSHdG1+3Y5DDjxTD46WkT/OVQHl142mJ4NYRwt5ox9c9Z7gsQEyfRffl2m74oMyYS8tpj+4Rmlr9gPKomP2J0zyMOblxQ5UyKzpgVjU00gTKD4zylD+lilJgaX2jmQsdJr331GAfjyi2Y=
  # GITHUB_RELEASE_TOKEN
  - secure: dYnnXy1GTp0RXqZCmp1ya4Tywxxvcgxqd6cubZo7hUEoyWaWJOMXcJirWFGlcVchMjiFNMNQwkroobHgKEitHqlS1Mjjtw1Q2JaMq+4m2EIt0DqXovQKuijngIrYPYMkEoDw633czqafLFL2AgebxXAitBdBDHmcjLej9Bok9faImojteLO3jQWRTtHyd6VKNMvUVulPUopPVgHNR/ibUNVmZXjQ+SvOrmTIU1srWb94bA9r86YF54P8BqHBkqZDF29u1X9dednbybym/jcLsNld9Imgt5jkz5/m5MXHLRJiKQzGHbBQZNc6mxAlGSND0FFBRqeaGPkhiMbVzGNElTmIAk/bx634VhNlGww8AKRz8YmlPxfSmNHgPVmTgPc2s8jJoBiBbNjazRBCcTPOVhwgB67h0hwSapxWH7wExIu+kisbrThW6WrM0b7ZkNdA9VZY2Tq6aetkLOO5UYk39FNREJZkaLAwL8EYBHtZ4glXuVD28LgXQma2qkXKgi/sb+dCza2SDz3IIqgCFIUtHwLWdyjlsJpo5ImL3wIytrD+9FfyoMKL26exu76EoPM+WjqnMhmkfJ6Uw6VMT4SSCfENtyWL7Xl2eDmpGLLp0uVwCl0dG7LyBbGzMPYD7Gs5dinhbKqownBU3WYgLdU238yKNdolEq1bRir+TeKUQBY=
