language: node_js
node_js:
- 4
sudo: false
script:
- npm run test:lint:js
- wct --skip-plugin local
after_success:
- '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && [ "x$TRAVIS_TAG" != "x" ] && npm run publish:cdn'
env:
  global:
    # CDN_SECRET
    - secure: CzFjtv/fVK41C4vV7bbXzTEIgtYJbT6hseHxOLrv/Oxan3lkgj0+H3tsHzYjwjXORcRbqlZrURKeh2RZFbduWuXVtqa6Q2O/NSgao5JBtIL0A8hQM8kmGyAMbNJ9sAKJlf4RTE4ORNASwwN9v3l9/kWtD2bL5LbDXxTLy/qYUNIHn4KbUWFiRntXIo9bH2XezLqJPoTo2pNYfgafzuRNJFTo+tMQrKfzMMtByg0p8QFZOJbJd53Z4HpumS7DWO1TUlcByX8rpIWGBeG02SXJHY1JFrl9+H+1q5ZjMlRcUWcU6l2ctCYrPdHGIdR6ANf9Fn1h5xCSup9vDKBDRQbD2gjqD4rdt00fe0jWkwKTD6mEaTs/Rh+0IffU2tgwFj8kayyYOD6vet5etKu8mUf92X7ePIxW31lvSvcU4scOgk5ReMA/ZcCdcZ9GMsaSr64t9i9nEKbdBuZuEdTslDE5l0uGCQPLALYWNWELDqK115f/AP96LaL2H+7jaXw6xM1cSiefHlImiPahu9T+N0ApN8JGUZo7tMkKnCvUXOQQk0XeX8tyA1gJ5V9QpjegIq2HehPwvxjh0ANmCfeG6W6PGALpQRDmYXgp0pXEK066E5Fd7jpJuxizdRQlKwfp3PHYCtIlEPOWm5GoJXKaA2BmcH5ZQj7mx4lY6i2iNihhrYg=
addons:
  sauce_connect:
    username:
      secure: "CYhC0bEfUSkXfRPhLAwMNcnKrxwMBwhzr3Ri9Paq0kMDX31J/cuAtMG/znpMotyXoRx6FLJ0vC7ikngQ7YxpYhFJtAf1oP20Lo6JXT7qRowAzzG52yyGQ5WkiicDxehuDbiD+qCec6FdAoimM/X+jtn1CvlN7yqUAbL0yEQD+JbXF3C2OyWZedLli/d6a7YlJsQSn2jPThg4jHPMODOxt3rOPlTbt6f1i+QOL+A1LDzuBy2kghHfRdpetJAG9GcnKsD3Dm982y3zQmKN7iQ4TdpFosHHdGnJEo/SEEY3fhaFznwwiX8J/6UHbkpsIFK5pSOXo9+4WylHqUc++3vJIB8W+ac5ZBBN/O7Je8KdaXmcmusKGhLOIkaGDxhSjyKyK9HfATeT5o5iyIIUD3Y0JU5fXHi2cSUwdp+cdIexeLcY3RYVcGUcrvB3xXa90SqnhukTGsgqe7Yqi/NxVNXevRgnwI5f/cZ6eoqyzVMYPswOxW+CHtCqyGwQ66pdT9D7TfwPiP2hfYQzQbheTk9FJ2TZnC1Hzjbb8ca+nvMfyGKCeXTxZPZTolwhSjFJpQQ3XTaCeXwTgrp14mo0uffyQ/+LL6OX/BiqKUpqLweT0BDgiW26WgYFJuPnbnI2mJiinIqB+dzeB5YgFIgS7MQzrxSddgafMQre7+ztfddB//4="
    access_key:
      secure: "grvf00t92P5TQwjH5lh5R3EUR4hG8Sj7TcZjeB1uLSMikcD0NGgFSVE4Xckv9Tndbk4Ak3crPY90CHcKVwyhZftgsiCeci7IMm6TaloIJ6a4omBOvWg80um8GaswJ1frEPJW/a99+YCgX8tbJ2K0tJWOJGUeoKtT1j77+2bPx8TlNTxqnDsioGXqLO+saaQ+VarawbmC13hZzFOT3g5JAg2shj+oFX8wke1so+pNAwRF1Ogw1N5U62oiN9/0hldeJnHguzZ1Ch9IvueuOhtTbo4icHJ2vAiKlvOxYeDlh9L8I5p/MlvTqwOB5/UJrVTZY9uEBazVmDe8wljtknEh2DP6ArHthmD18hVi/5NK1HEPAtYvvohMobnAHjCeSBpnBykX2/4bQicMCQj3eJxY+b4xRLPAcJwUNhSAipK+GKH0yQVph4FXobyhW74LkM4xpTBjXjaCGT3n/Oz7umhhYqh2XE6mOE7DzSxeJlMSQaYLY39qdC5dW+jipxQZASSesdayOhNmWnU0yAXCXFTiS96O04ANpfu3uDsYjqj3IamklmdOUL221p1J5N7m/izNcSrB9JFM/gRTN7BMA5/m9JwpHt/EeR4gWvSlTR4O0lkeb8dMbDm95t5v7A6otJHAm97eDmydjhaNL4X8yYJOeSSO27DZLGmFaouzU053/JY="
