name: CI
on: pull_request
jobs:
  test:
    name: Test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Lint (JavaScript)
        run: npm run lint:js
      - name: Lint (Polymer)
        run: npm run lint:wc
      - name: Unit Tests (headless)
        run: npx polymer test --config-file wct.conf.local.json
      - name: Unit Tests (SauceLabs)
        run: npx polymer test --config-file wct.conf.sauce.json
        env:
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY_DESIRE2LEARN }}
          SAUCE_USERNAME: Desire2Learn
